### ISSUE TITLE
PHP update

### ISSUE THREAD

**Issue by damda58** [EyesOfNetworkCommunity/eonweb#101]
Hello,
is it possible to update php on an eon server?
Because version 5.4 is old and I need at least version 5.5 to set up personal scripts.
If so, is there a procedure?

**Comment by Julien1498** [comment]
Hello @damda58,
There is no procedure yet but we are currently working on a new version of eon with PHP8. It will be available in the coming months.

**Comment by damda58** [comment]
When I want to uninstall php-common to install the new one here is what I have in dependencies. How to do so that it does not delete eon nagios etc ...?

![image](https://user-images.githubusercontent.com/6893451/135837679-7ae8892d-ca4b-4b79-9424-c05077f558df.png)

**Comment by Julien1498** [comment]
You can use : rpm -e --nodeps "yourpackage"
