### ISSUE TITLE
Fonctionnalités interface graphique

### ISSUE THREAD

**Issue by dcastera** [EyesOfNetworkCommunity/eonweb#11]
Le menu de gauche se réinitialise à chaque changement de page.
Il serait souhaitable que le menu reste déployé lorsqu'on clique sur une entrée pour un confort de navigation.

**Comment by IPv777** [comment]
Ce n'est plus le cas dans les version d'EoN les plus récentes.
L'issue peut être fermée.
@davoult

**Comment by davoult** [comment]
@IPv777 merci, en effet ce problème n'est plus présent dans les versions récentes.
@dcastera dans quelle version d'eonweb ce problème est rencontré ? ($ rpm -qi eonweb)

**Comment by dcastera** [comment]
Name        : eonweb
Version     : 5.1
Release     : 0.eon
Architecture: x86_64
Install Date: sam. 04 nov. 2017 12:16:14 CET
Group       : Applications/System
Size        : 21074662
License     : GPL
Signature   : DSA/SHA1, lun. 20 fÃ©vr. 2017 09:56:35 CET, Key ID 5500c92e166f78cf
Source RPM  : eonweb-5.1-0.eon.src.rpm
Build Date  : lun. 20 fÃ©vr. 2017 09:56:17 CET
Build Host  : build7
Relocations : (not relocatable)
Summary     : EyesOfNetwork Web Interface
Description :
EONWEB is the web frontend for the EyesOfNetwork appliance : https://www.eyesofnetwork.com.

**Comment by OscarPoels** [comment]
Après avoir testé cela sur la même version (c'est à dire en 5.1-0), il se trouve que le bug ne s'est pas présenté pour ma part :

<img width="564" alt="Capture 5 1" src="https://user-images.githubusercontent.com/28846880/103521967-f0a0a000-4e79-11eb-96e3-8be40330a88f.PNG">

![Menu bug 5 1](https://user-images.githubusercontent.com/28846880/103521998-fdbd8f00-4e79-11eb-8c0e-eacd6d935c20.gif)

Le bug n'étant également pas présent dans la dernière version, en 5.3, je clos cette issue.
