### ISSUE TITLE
left menu not show

### ISSUE THREAD

**Issue by bonois23** [EyesOfNetworkCommunity/eonweb#2]
hello ,
i have a problem with menu bar admin in the left .

**Comment by vfricou** [comment]
Hello, 

You've try with which browser ? 

Typicaly, with firefox and chrome (or chromium) I no see any problems with foldable menu on latest build (downloadable iso on website)

Could you much explain the problem ? The menu not work or is totaly not displayed ?

**Comment by vfricou** [comment]
Could you see too if you've not masked the menu with button top bar with two arrow ?

**Comment by bonois23** [comment]
the menu left and top menu are masked for admin and all users .

**Comment by vfricou** [comment]
Could you give us some informations : 
- Browser used in this case (and version)

Could you send us a screenshot of the board ?

**Comment by bonois23** [comment]
Resolved , i reinstall eon ,restore all template . Thanks.

**Comment by carrie0307** [comment]
May I ask you how to install eonweb? I can't find the page to install.

Thank you very much!
