### ISSUE TITLE
How to set IP address  

### ISSUE THREAD

**Issue by fellagmb** [EyesOfNetworkCommunity/eonweb#37]
I install the iso eyesofnetwork but is coming in command line interface. How can i set my ip address and access the application on web and add my devices. Thanks

**Comment by rverchere** [comment]
Hello,

EON is base on CentOS 7, so you can change your IP like any other CentOS distro:
https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/networking_guide/sec-Configuring_IP_Networking_with_nmtui
