### ISSUE TITLE
MySQL security

### ISSUE THREAD

**Issue by IPv777** [EyesOfNetworkCommunity/eonweb#62]
Hello,

for a security reasons :

- could you change the default password of MySQL database which is actually root66 ?
- the MySQL server is actually listening on 0.0.0.0, could it be possible to listen only on loopback interface ?

Thanks

**Comment by davoult** [comment]
Hello,

By default all SQL Users can only connect from 127.0.0.1:

``` 
MariaDB [(none)]> SELECT Host,User FROM mysql.user;
+-----------------------+-------------+
| Host                  | User        |
+-----------------------+-------------+
| 127.0.0.1             | root        |
| ::1                   | root        |
| localhost             |             |
| localhost             | cacti       |
| localhost             | eonweb      |
| localhost             | gedadmin    |
| localhost             | lilac       |
| localhost             | notifierSQL |
| localhost             | root        |
| localhost.localdomain |             |
| localhost.localdomain | root        |
+-----------------------+-------------+
11 rows in set (0.00 sec)
```

**Comment by IPv777** [comment]
Ok for the weak password, I can be ok if only localhost can connect with it.

But why listen on 0.0.0.0:3306 ?
It's an unnecessary risk 🤔

Could you consider to add `bind-address = 127.0.0.1` in the `[mysqld]` block of `/etc/my.cnf` ?
then `service mariadb restart` and `netstat -tulpn | grep LISTEN` to check.
I tested on my EoN : it's ok

**Comment by Julien1498** [comment]
Thanks for your reply, it will be added in a next update.
