### ISSUE TITLE
EON themes of Active Directory accounts

### ISSUE THREAD

**Issue by drouot** [EyesOfNetworkCommunity/eonweb#63]
When I'm connect with a local account, I can see in my profil EON themes but I can't see them when I'm connect with a Active Directory account.
![Bug_profil](https://user-images.githubusercontent.com/65652729/82427148-fe3f1c00-9a88-11ea-8856-e6e0e827154f.PNG)

**Comment by Julien1498** [comment]
Fix and merged #71
