### ISSUE TITLE
CSS timeout when using Default theme

### ISSUE THREAD

**Issue by rverchere** [EyesOfNetworkCommunity/eonweb#65]
With the new theme functionnality, when going to Lilac configuration part, eonweb load `custom-lilac.css` and `custom.css`.

But this file is only available for the new themes, not the old (Default, ClassicV5) ones, leading to CSS timeout.

![image](https://user-images.githubusercontent.com/232433/84907875-0a33f300-b0b4-11ea-8f3d-574b352418b9.png)

**Comment by Julien1498** [comment]
Fix in "gestion_theme" branch on eonweb and lilac.
