### ISSUE TITLE
Special caracters in ged fields

### ISSUE THREAD

**Issue by jeanphilippelevy** [EyesOfNetworkCommunity/eonweb#7]
Unable to acknowledge when ? in hostname

**Comment by mlh56** [comment]
La présence du caractère ' dans le champs Service empêche l’acquittement d'un évènement.
Le contournement trouvé est d'acquitter en CLI cet évènement avec les commandes : 

Se connecter sur le serveur EON
Repérer l'évènement à l'aide de la commande 
/srv/eyesofnetwork/ged/bin/gedq -peek -type 1 |grep -A 2 EXEMPLE

Exemple de retour:
# /srv/eyesofnetwork/ged/bin/gedq -peek -type 1 |grep -A 2 EXEMPLE
      <equipment key="true" meta="false">EXEMPLE</equipment>
      <service key="true" meta="false">Prise en charge de l’impression</service>
      <state key="true" meta="false">2</state>

Acquitter l'évènement avec la commande en indiquant les éléments récupérés dans le retour de la commande précédente.

/srv/eyesofnetwork/ged/bin/gedq -drop -type 1 -queue active 'EXEMPLE' 'Prise en charge de l’impression' '2'

L'alerte ne doit plus être présente sur la console EONWEB.

**Comment by Julien1498** [comment]
Fixed in lilac sql_php8 branch
