### ISSUE TITLE
[ITSM Module] Directory not found and permissions issue

### ISSUE THREAD

**Issue by ChamMach** [EyesOfNetworkCommunity/eonweb#70]
Hi, 

Issues encountered on **EON 5.3-5**.

When I upload a file via the ITSM module, I have some errors described below : 

![image](https://user-images.githubusercontent.com/23166349/94993938-af57d600-0594-11eb-8bff-784a54553228.png)
![image](https://user-images.githubusercontent.com/23166349/94993945-bbdc2e80-0594-11eb-8e89-0f380c9f9fd9.png)
![image](https://user-images.githubusercontent.com/23166349/94994005-20978900-0595-11eb-8305-779e8628691a.png)

Within some investigation I found the problem. The folder **uploaded_file** in **/srv/eyesofnetwork/eonweb/module/admin_itsm** is not created automatically with **function_itsm.php**. 

Also, the file is added with the **apache user (and group)** so there is some problem with permission as we can see on the second and third picture.

Can you resolve theses issues please ? 

Thank you

**Comment by ChamMach** [comment]
Ping @jeremyHoarau & @davoult

**Comment by ChamMach** [comment]
Ping x2 @jeremyHoarau & @davoult

**Comment by Julien1498** [comment]
Fixex and merged #72
