### ISSUE TITLE
Bug Grafana with Theme "EONFlatLight" and "EONFlatDark"

### ISSUE THREAD

**Issue by drouot** [EyesOfNetworkCommunity/eonweb#75]
Bonjour,
Avec le thême EON par défaut, lorsque l'on clique sur une sonde composée d'un graph Grafana et que l'on clique sur ce graph,  celui-ci s'ouvre automatiquement dans un nouvel onglet du navigateur.
Cependant, cette option ne fonctionne pas pour les autres thêmes de EON. Lorsque l'on clique sur le graph Grafana, celui-ci s'ouvre dans la même fenêtre du navigateur et conserve le menu EON à gauche proposant ainsi un rendu de visualisation réduit de la page Grafana par rapport à celle d'un nouvel onglet de navigateur.
![bug_Grafana_ThemeEON](https://user-images.githubusercontent.com/65652729/96722951-3e932500-13ae-11eb-9581-0524cb80bea0.PNG)

**Comment by OscarPoels** [comment]
Bonjour Raphael,
Pouvez-vous me dire quelle version d'EON possédez vous ?
Je ne retrouve pas le même problème sur la version 5.3-7. Comme vous pouvez le constater, tous les thèmes conserve normalement le menu de gauche : 
<img width="960" alt="GrafanaEONLight" src="https://user-images.githubusercontent.com/28846880/99940171-f16af000-2d6b-11eb-84af-40a058516ffd.PNG">
<img width="959" alt="GrafanaDark" src="https://user-images.githubusercontent.com/28846880/99940179-f4fe7700-2d6b-11eb-87ef-521682464379.PNG">
<img width="959" alt="GrafanaDefault" src="https://user-images.githubusercontent.com/28846880/99940188-f760d100-2d6b-11eb-9a63-b7466a173e5e.PNG">

Si votre problème subsiste et que vous tenez à ouvrir votre Graphana indépendamment de EON, je vous invite à rester appuyer sur la touche CTRL en même temps de cliquer sur votre graph, ce qui aura pour effet de vous ouvrir Graphana dans un nouvel onglet du navigateur.
![CTRLClique](https://user-images.githubusercontent.com/28846880/99941123-c5e90500-2d6d-11eb-88de-835c754723a1.gif)
