### ISSUE TITLE
[Bug] Service doesn't appear in search 

### ISSUE THREAD

**Issue by Davidffry** [EyesOfNetworkCommunity/eonweb#77]
Hi,

when typing in left search bar, we cannot search for service.

I targeting the issue : it's probably comes from the interpretation of the thruk json return in the ajax function.
![image](https://user-images.githubusercontent.com/31964077/98962338-d34cf680-2506-11eb-8fff-15c209ad4855.png)

the json return :
![image](https://user-images.githubusercontent.com/31964077/98962308-ccbe7f00-2506-11eb-9274-f9760a440370.png)

and the files : `/srv/eyesofnetwork/eonweb/js/side.js`

**Comment by Julien1498** [comment]
Fix #78
