### ISSUE TITLE
/module/admin_conf/download.php $_GET["file"] variable exists arbitrary file download vulnerability

### ISSUE THREAD

**Issue by hi-KK** [EyesOfNetworkCommunity/eonweb#8]
Hello, I found that there are some problems with eonweb, hoping to help you and your work
[/module/admin_conf/download.php](https://github.com/EyesOfNetworkCommunity/eonweb/blob/master/module/admin_conf/download.php)
```php
if(isset($_GET["file"])){
	$dwn="/tmp/".$_GET["file"];
	header("Content-type: application/octet-stream");
	header("Content-Disposition: attachment; filename=".$_GET["file"]);
	flush(); 
	readfile($dwn);
}
```
'$_GET["file"]' is not filtered,and  exists arbitrary file download vulnerability
So when we open this url:
[https://localhost/module/admin_conf/download.php?file=../../etc/passwd](https://localhost/module/admin_conf/download.php?file=../../etc/passwd
)
it would download the file '/etc/passwd'
<img width="427" alt="1" src="https://user-images.githubusercontent.com/15962497/29880806-55fa198a-8ddb-11e7-8575-7f445665cc34.png">
and we can get the contents of this file
<img width="373" alt="2" src="https://user-images.githubusercontent.com/15962497/29880934-bb21475c-8ddb-11e7-8151-510037135568.png">

**Comment by jeanphilippelevy** [comment]
Fix here :
[3163221240db69d417cf6bb8456f87653d472f21](https://github.com/EyesOfNetworkCommunity/eonweb/commit/3163221240db69d417cf6bb8456f87653d472f21)

Thank you for the advice !
