### ISSUE TITLE
Issue with notification on eonweb

### ISSUE THREAD

**Issue by OscarPoels** [EyesOfNetworkCommunity/eonweb#80]
When trying to edit a rule in the advanced notification into nagios, it disapears and doesn't seems like to be mofidied into the database. 
Editing the rule :

<img width="768" alt="Capture5" src="https://user-images.githubusercontent.com/28846880/101461155-c9b68300-393a-11eb-90e0-1c35bfeccc18.PNG">

The rule disapear :

<img width="772" alt="Capture6" src="https://user-images.githubusercontent.com/28846880/101461177-ce7b3700-393a-11eb-8b87-d0deaf8ffae3.PNG">

Dosen't get modified into the database :

<img width="881" alt="Capture8" src="https://user-images.githubusercontent.com/28846880/101461186-d1762780-393a-11eb-89b2-9ad897789ff9.PNG">

**Comment by jeremyHoarau** [comment]
Hello,
We found multiple problems due to the changement in the sql request. 
First, we found that in an update requests an id parameter is missing. 
Secondly when we update or add a rule, the rule_method wasn't populated due to an error in the way the sql response is retrieved.

**Comment by davoult** [comment]
Fix is now available in [5.3-10](https://github.com/EyesOfNetworkCommunity/eonweb/releases/tag/5.3-10)
