### ISSUE TITLE
Module dp_admin cannot add hosts regression

### ISSUE THREAD

**Issue by rverchere** [EyesOfNetworkCommunity/eonweb#85]
After eonweb 5.3-10 upgrade, we cannot add hosts in bp_admin module.

Regression has been introduced with this commit https://github.com/EyesOfNetworkCommunity/eonweb/commit/bdccea095a63b50dad7e9005c8e9956aaafd3452

**Comment by Julien1498** [comment]
Hello, 
Thanks you for the information. You can find the fix in the "admin_bp" branch.
