### ISSUE TITLE
MAJ Eonweb 5.3.10

### ISSUE THREAD

**Issue by rodrigoglucena** [EyesOfNetworkCommunity/eonweb#94]
Bonjour, 

J'aimerais MAJ eonweb en version 5.3.10, cependant je ne trouve pas de doc .

J'ai modifié les fichiers dans /srv/eyesofnetwork et redémarré apache.

En vous remerciant beaucoup,

Rodrigo

**Comment by Julien1498** [comment]
Bonjour,

Sur quelle version vous êtes actuellement ? Si vous êtes sur une version 5.3.* un "yum update" devrait suffire

**Comment by rodrigoglucena** [comment]
ok merci, je suis effectivement sur la 5.3.

Je vais tester.
